### ISSUE TITLE
BUG: 1.2 raises error w.r.t. object has no attribute '__name__'

### ISSUE THREAD

**Issue by bashtage** [numpy/numpydoc#362]
Just saw in the statsmodels build log

```
Extension error (numpydoc.numpydoc):
Handler <function mangle_signature at 0x7f0833af8f70> for event 'autodoc-process-signature' threw an exception (exception: 'HuberScale' object has no attribute '__name__')
make: *** [Makefile:39: html] Error 2
Error: Process completed with exit code 2.
```

**Comment by bashtage** [comment]
Log at https://github.com/statsmodels/statsmodels/runs/4938693436?check_suite_focus=true

**Comment by rossbar** [comment]
Thanks for reporting - ironically, the path that raises the exception is attempting to provide more detailed information for a UserWarning. This is a bug in numpydoc that arises from the assumption that `Callable`'s always have a `__name__` attribute; which was triggered in this case by:

```python
class MyFunction():
    def __init__(self):
        pass
    def __call__(self, *args):
        pass

my_function = MyFunction()
```

Fortunately, there is an easy fix for the particular instance reported (see statsmodels/statsmodels#8044), but this should be fixed in numpydoc as well.

**Comment by bashtage** [comment]
Thanks for fixing.  Was better for us to fix our docs.
